config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions', confirmations: 'users/confirmations' }

  get 'companies/filter', path: 'companies/filter'

  resources :groups

  resources :companies do
    member do
      get 'dashboard'
      get 'subscription_packages'
      get 'update_subscription_package'
      get 'display_surveys'
    end
  end

  resources :company_settings
  resources :user_settings
  resources :members do
    member do
      get 'calculate_surveys'
    end
  end

  resources :surveys do
    member do
      get 'survey_charts'
    end
    collection do
      get 'add_question'
      get 'add_option'
      get 'delete_option'
      get 'delete_question'
    end
    resources :user_responses
  end

  resources :home do
    collection do
      get 'index'
      get 'filter_category'
      get 'sign_in'
      post 'sign_in_redirect'
    end
  end

  get "*path", to: 'application#page_not_found'

  get :dashboard, to: 'companies#dashboard'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action do
    if user_signed_in?
      redirect_to dashboard_company_path(@current_company)
    end
  end

  # get home/index
  def index
    @surveys = Survey.get_public_surveys(params[:page], PER_PAGE_SURVEYS)
    @categories = Survey::CATEGORIES
    respond_to do |format|
      format.html
    end
  end

  def filter_category
    @categories = Survey::CATEGORIES
    @surveys = Survey.get_public_surveys(params[:page], PER_PAGE_SURVEYS, params[:filter_by])
    respond_to do |format|
      format.js
    end
  end

  def company_redirect
    @companies = Company.unscoped.all
  end

  def sign_in
    respond_to do |format|
      format.html
    end
  end

  def sign_in_redirect
    user = User.unscoped.find_by_email(params[:email])
    respond_to do |format|
      if user.present?
        format.html { redirect_to subdomain: user.company.subdomain, controller: 'users/sessions', action: 'new' }
      else
        flash[:error] = I18n.t 'user_not_found'
        format.html { render :sign_in }
      end
    end
  end
end

app/views/home/_public_surveys.html.erb
<div class="row">
  <% if surveys.blank? %>
    <h4 class="text-muted"><%= t('home.no_public_surveys_available') %></h4>
  <% else %> 
    <% surveys.each do |survey| %>
      <div class="col-lg-4">
        <div class="mx-auto mt-4">
          <div class="card">
            <h5 class="card-header"><%= survey.name %> <span class="badge badge-pill badge-secondary mx-2"><%= survey.category %></span></h5>
            <div class="card-body d-flex align-items-center flex-column">
              <p class="card-text"><%= survey.description %></p>
              <%= link_to t('user_responses.response_label'), new_survey_user_response_path(survey), class: "primary-btn" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="apple_pagination d-flex justify-content-center mt-4">
    <%= will_paginate surveys %>
  </div>
<% end %>

app/views/home/companies_list.html.erb
<div class="row no-gutters">
  <div class="col"></div>
  <div class="col-8 col-md-6 content-window p-20 d-flex align-items-center flex-column">
    <h2><%= t 'companies.companies_list_label' %></h2><br>
    <% @companies.each do |company| %>
      <%= link_to new_user_session_url(subdomain: company.subdomain, email: @email) do %>
        <div class="primary-btn w-50">
          <%= company.name %>      
          </div>
      <% end %><br>
    <% end %>                
  </div>
  <div class="col"></div>
</div>

<%= render partial:'layouts/footer' %>

app/views/home/filter_category.js.erb
$("#public_surveys_container").fadeOut('slow', function(){
  $("#public_surveys_container").html("<%= escape_javascript(render partial: 'public_surveys', locals: { surveys: @surveys, categories: @categories }) %>").fadeIn();
});

app/views/home/index.html.erb
<%= render partial:'layouts/flash_messages' %>
<!-- Master Head -->
<header class="master-head text-white text-center">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <h1 class="mb-5"><%= t('home.greeting_message') %></h1>
      </div>
    </div>
  </div>
</header>

<!-- Public Surveys -->
<section class="packages text-center bg-light">
  <div class="container">
    <h2 class="mb-5"><%= t('home.fill_surveys_message') %></h2>
    <div class="dropdown mx-2 mb-2" id="filter-dropdown">
      <button class="secondary-btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"><%= t('home.filter_label') %></button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to t('home.filter_all_label'), filter_category_home_index_path(filter_by: nil), class: "dropdown-item", remote: true %>
        <% @categories.each do |category| %>
          <%= link_to category, filter_category_home_index_path(filter_by: category), class: "dropdown-item", remote: true %>
        <% end %>
      </div>
    </div>
    <div id = "public_surveys_container">
      <%= render partial: 'public_surveys', locals: { surveys: @surveys, categories: @categories } %>
    </div>
  </div>
</section>
<%= render partial:'layouts/footer' %>

app/views/home/sign_in.html.erb
<div class="row">
  <div class="col-sm-6 p-20" >
    <%= render partial:'layouts/flash_messages' %>
    <div class="d-flex justify-content-center">
      <h1><%= t('login_label') %></h1>
    </div>

    <div class="p-l-30">
      <%= form_tag({controller: 'home', action: 'companies_list'}, method: "post", class: "nifty_form") do %>

        <div class = "label-input-container mt-4">
          <div class="label-input-item row no-gutters">
            <%= label_tag :email, nil, class: "col-4" %> <br />
            <%= text_field_tag :email, params[:email], class: "col-8", required: true %>
          </div>
        </div>

        <div class = "input-label-container my-4">
          <div class="actions">
            <%= submit_tag(t(:submit_label), class: 'primary-btn w-100') %>
          </div>
        </div>
      <% end %>
    </div>
    <%= render partial:'layouts/footer' %>
  </div>
  <div class="col-sm-6" >
    <img src="/assets/survey.jpeg" class = "img-fullsize"  alt="survey">
  </div>
</div>