config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions', confirmations: 'users/confirmations' }

  get 'companies/filter', path: 'companies/filter'

  resources :groups

  resources :companies do
    member do
      get 'dashboard'
      get 'subscription_packages'
      get 'update_subscription_package'
      get 'display_surveys'
    end
  end

  resources :company_settings
  resources :user_settings
  resources :members do
    member do
      get 'calculate_surveys'
    end
  end

  resources :surveys do
    member do
      get 'survey_charts'
    end
    collection do
      get 'add_question'
      get 'add_option'
      get 'delete_option'
      get 'delete_question'
    end
    resources :user_responses
  end

  resources :home do
    collection do
      get 'index'
      get 'filter_category'
      get 'sign_in'
      post 'sign_in_redirect'
    end
  end

  get "*path", to: 'application#page_not_found'

  get :dashboard, to: 'companies#dashboard'
end

app/models/company.rb
class Company < ActiveRecord::Base
  FILTER_TYPE = { name: 'name', survey_type: 'survey_type', created_on: 'created_on', created_by: 'created_by', expired_before: 'expired_before' }

  belongs_to :subscription_package
  has_one :company_setting, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :user_responses, dependent: :destroy
  has_many :group_members, dependent: :destroy
  has_many :surveys, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :options, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :user_settings, dependent: :destroy
  has_many :activities, dependent: :destroy

  after_create do
    CompanySetting.create(
      :max_questions => 100,
      :supervisors_survey_permission => '1',
      :supervisors_settings_permission => '1',
      :members_settings_permission => '1',
      :survey_expiry_days => 5,
      :company_id => self.id)    
  end

  scope :user_companies, -> (email) { Company.joins('INNER JOIN users on users.company_id = companies.id').where("users.email = ?", email) }

  def dashboard_resources(user)
    user_setting = user.user_setting
    company_setting = user.company.company_setting
    [company_setting, user_setting]
  end 

  def filter_surveys(filter_name, options)
    if filter_name == FILTER_TYPE[:name]
      @surveys = surveys.filter_by_name(options[:value])
    elsif filter_name == FILTER_TYPE[:expired_before]
      @surveys = surveys.filter_by_expiry(options[:value])
    elsif filter_name == FILTER_TYPE[:survey_type]
      @surveys = surveys.filter_by_survey_type(options[:value])
    elsif filter_name == FILTER_TYPE[:created_on]
      @surveys = surveys.filter_by_created_at(options[:value])
    elsif filter_name == FILTER_TYPE[:created_by]
      @surveys = surveys.filter_by_created_by(options[:value])
    end
  end

  validates :name, presence: true, uniqueness: true, length: { maximum: 30 } 
  validates :subdomain, presence: true, uniqueness: true, length: { maximum: 30 }

  def self.current_id=(id)
    Thread.current[:tenant_id] = id
  end

  def self.current_id
    Thread.current[:tenant_id]
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!

  before_action only: [:filter, :display_surveys] do
    @surveys = Survey.all
  end

  def dashboard
    add_breadcrumb "Dashboard", dashboard_company_path(@current_company)
    @activities = @current_company.activities.get_user_activities(current_user)
    @surveys_stats = [@current_company.surveys.expired_surveys.count,
                      @current_company.surveys.active_surveys.count]
    @latest_surveys_labels = @current_company.surveys.latest_surveys.limit(3).pluck(:name)
    @latest_surveys_responses_count = @current_company.surveys.latest_surveys_responses(3)
    respond_to do |format|
      format.html
    end
  end

  def subscription_packages
    add_breadcrumb "Subscription Packages", subscription_packages_company_path(@current_company)
    @subscription_packages = SubscriptionPackage.first(3)
    respond_to do |format|
      format.html
    end
  end

  def update_subscription_package
    @current_company.subscription_package_id = params[:id]
    if @current_company.save
      respond_to do |format|
        flash[:notice] = I18n.t 'package.subscription_package_update_label'  
        format.html { redirect_to dashboard_company_path }
      end
    else
      flash[:error] = @current_company.errors.full_messages
      format.html { redirect_to subscription_packages_company_path(current_user) }
    end
  end

  def filter
    if params[:filters].present? && params[:options].present?
      @surveys = @current_company.filter_surveys(params[:filters], params[:options])
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|  
        format.html { redirect_to display_surveys_company_path(current_user) }
      end
    end
  end

  def display_surveys
    @employees = @current_company.users
    add_breadcrumb "Surveys", display_surveys_company_path(@current_company)
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/views/companies/_list_surveys.html.erb
<table class="table js-data-table w-100">
  <thead>
    <tr>
        <th scope="col"><%= t 'serial_num_label' %></th>
        <th scope="col"><%= t 'title_label' %></th>
        <th scope="col"><%= t 'survey_type_label' %></th>
        <th scope="col"><%= t 'category_label' %></th>
        <th scope="col"><%= t 'created_by_label' %></th>
        <th scope="col"><%= t 'created_on_label' %></th>
        <th scope="col"><%= t 'expiry_label' %></th>
        <th scope="col"><%= t 'options_label' %></th>
      </tr>
    </thead>
    <tbody>
      <% @surveys.each.with_index(1) do |survey, index| %>
        <tr>
        <td scope="row"><%= index %></th>
        <td class="link-text"><%= link_to survey.name, survey_path(survey.id), class: "text-small" %></td>
        <td><%= survey.survey_type %></td>
        <td><%= survey.category %></td>
        <td><%= survey.user.full_name %></td> 
        <td><%= survey.created_at.to_s(:long) %></td>
        <td><%= survey.expiry.to_s(:long) %></td>
        <td class="table-icon">
          <% if can? :survey_charts, survey %>
            <%= link_to survey_charts_survey_path(survey) do %>
              <i class="fa fa-line-chart mr-2"></i>
            <% end %>
          <% end %>
          <% if (can? :edit, survey) && (survey.expiry > DateTime.now) %>
            <%= link_to edit_survey_path(survey) do %>
              <i class="fa fa-pencil mr-2"></i>
            <% end %>
          <% end %>
          <% if can? :destroy, survey %>
            <%= link_to survey_path(survey), method: :delete, data: { confirm: t('links.confirmation_message') } do %>
              <i class="fa fa-trash"></i>
            <% end %>
          <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/dashboard.html.erb
<div class="container-fluid">
  <% if @user_setting.show_graphs? %>
    <div id="graphs">
      <div class="d-flex justify-content-center heading-bg mb-2">
        <h1><%= t 'dashboard.graphs_label' %></h1>
      </div>
      <%= render partial: 'layouts/main_charts', locals: { stats_data: @surveys_stats, stats_labels: @surveys_stats_labels, latest_surveys_labels: @latest_surveys_labels, latest_surveys: @latest_surveys_responses_count } %>
    </div>
  <% end %>
  <% if @user_setting.show_history? %>
    <div id="histroy" class="p-t-20">
      <div class="d-flex justify-content-center heading-bg mb-2">
        <h1><%= t 'dashboard.history_label' %></h1>
      </div>
      <%= render partial: 'layouts/activity_history', locals: { user_activities: @activities } %>
    </div>
  <% end %>
</div>

app/views/companies/display_surveys.html.erb
<div>
  <div class="d-flex justify-content-center heading-bg mb-2">
    <h1><%= t('public_surveys.surveys_label') %></h1>
  </div>
  
  <div class="row no-gutters justify-content-between">
    <div class="dropdown">
      <button class="secondary-btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown">
        <%= t('public_surveys.filter_label') %>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a href="#_" class="dropdown-item" data-toggle="modal" data-target="#name_modal"><%= t('public_surveys.name_label') %></a>
        <a href="#_" class="dropdown-item" data-toggle="modal" data-target="#survey_type_modal"><%= t('public_surveys.type_label') %></a>
        <a href="#_" class="dropdown-item" data-toggle="modal" data-target="#expired_before_modal"><%= t('public_surveys.expired_before_label') %></a>
        <a href="#_" class="dropdown-item" data-toggle="modal" data-target="#created_on_modal"><%= t('public_surveys.created_on_label') %></a>
        <a href="#_" class="dropdown-item" data-toggle="modal" data-target="#created_by_modal"><%= t('public_surveys.created_by_label') %></a>
      </div>
    </div>
    <div class="col-2 mb-2">
      <% if can? :create, Survey %>
        <td><%= link_to t('surveys.new_survey_link'), new_survey_path, class: 'primary-btn' %></td>
      <% end %>
    </div>
  </div>

  <% if @surveys.size > 0 %>
    <%= render partial: 'shared/filters/name_filter' %>
    <%= render partial: 'shared/filters/survey_type_filter' %>
    <%= render partial: 'shared/filters/expired_before_filter' %>
    <%= render partial: 'shared/filters/created_on_filter' %>
    <%= render partial: 'shared/filters/created_by_filter', locals: { employees: @employees} %>  
  <% end %>
  
  <div id = "surveys_list">
    <%= render partial: 'list_surveys', locals: { surveys: @surveys} %>
  </div>
</div>

app/views/companies/display_surveys.js.erb
$("#surveys_list").html("<%= escape_javascript(render partial: 'list_surveys', locals: { surveys: @surveys } ) %>"); 

app/views/companies/filter.js.erb
$("#surveys_list").html("<%= escape_javascript(render partial: 'list_surveys', locals: { surveys: @surveys } ) %>");

app/views/companies/subscription_packages.html.erb
<!-- Packages -->
<section class="packages text-center bg-light">
  <div class="container">
    <h3>
      <%= t 'package.current_package_label' %>
      <%= current_user.company.subscription_package.subscription_package_name %></h3>
    <h2 class="mb-5"><%= t 'package.package_choose_label' %></h2>
    <div class="row">
      <%= render :partial => "layouts/package", collection: @subscription_packages, as: :subscription_package %>
    </div>
  </div>
</section>