config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions', confirmations: 'users/confirmations' }

  get 'companies/filter', path: 'companies/filter'

  resources :groups

  resources :companies do
    member do
      get 'dashboard'
      get 'subscription_packages'
      get 'update_subscription_package'
      get 'display_surveys'
    end
  end

  resources :company_settings
  resources :user_settings
  resources :members do
    member do
      get 'calculate_surveys'
    end
  end

  resources :surveys do
    member do
      get 'survey_charts'
    end
    collection do
      get 'add_question'
      get 'add_option'
      get 'delete_option'
      get 'delete_question'
    end
    resources :user_responses
  end

  resources :home do
    collection do
      get 'index'
      get 'filter_category'
      get 'sign_in'
      post 'sign_in_redirect'
    end
  end

  get "*path", to: 'application#page_not_found'

  get :dashboard, to: 'companies#dashboard'
end

app/views/layouts/_activity_history.html.erb
<div class="container activity-container p-0">
  <!-- if activities are available -->
  <% unless user_activities.blank? %>
  <div class="table-custom-scrollbar my-2">
    <table class="table table-bordered table-striped mb-0 js-data-table">
      <thead>
        <tr>
          <th scope="col"><%= t 'serial_num_label' %></th>
          <th scope="col"><%= t 'activity_history.activity_label' %></th>
          <th scope="col"><%= t 'activity_history.time_label' %></th>
        </tr>
      </thead>
      <tbody>
        <% user_activities.each.with_index(1) do |activity, index| %>
          <tr>
            <td scope="row"><b><%= index %></b></td>
            <td>
              <p>
                <!-- Following if else block displays owner's name or email and action of activity -->
                <% if activity.owner_id.present? %>
                  <%= activity.owner.full_name %> <%= activity.action %>
                <% else %>
                  <span class="badge badge-info"> <%= t('guest_user_label') %> </span>
                  <%= activity.parameters[:email] %> <%= activity.action %> 
                <% end %>
                <!-- Following if elsif block displays trackable object and its link if available -->
                <% if activity.trackable_survey? %>
                  <% if activity.trackable.present? %>
                    <%= link_to activity.trackable.name, survey_path(activity.trackable.id) %>
                  <% else %>
                    <%= activity.parameters[:trackable_name] %>
                  <% end %>
                <% elsif activity.trackable_group? %>
                  <% if activity.trackable.present? %>
                    <%= link_to activity.trackable.name, group_path(activity.trackable.id) %>
                  <% else %>
                    <%= activity.parameters[:trackable_name] %>
                  <% end %>
                <% elsif activity.trackable_user? %>
                  <% if activity.trackable.present? %>
                    <%= link_to activity.trackable.full_name, member_path(activity.trackable.id) %>
                  <% else %>
                    <%= activity.parameters[:trackable_name] %>
                  <% end %>
                <% elsif activity.trackable_user_response? %>
                  <%= link_to activity.trackable_type, survey_path(activity.trackable.survey_id) %>
                <% end %>
                <!-- Displays trackable object's type in a badge -->
                <span class="badge badge-primary"> <%= activity.trackable_type %> </span>
              </p>
            </td>
            <td><%= activity.created_at.to_s(:long) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <!-- when activites are not available  -->
  <% else %>
    <div class="d-flex justify-content-center empty-resource-box">
      <p><%= t 'activity_history.no_activity_label' %></p>
    </div>
  <% end %>
</div>

app/views/layouts/_company_settings_form.html.erb
<div class="col-10 p-3">
  <h3><%= t 'company_settings.company_settings_heading' %></h3>
  <%= form_for(@company_setting) do |c| %>
    
    <div class="form-group">
      <%= c.label :allow_supervisors_to_edit_my_settings, t('user_settings.supervisors_settings_permission_label') %>
      <%= c.check_box :supervisors_settings_permission %>
    </div>

    <div class="form-group">
      <%= c.label :allow_members_to_edit_my_settings, t('user_settings.members_settings_permission_label') %>
      <%= c.check_box :members_settings_permission %>
    </div>    

    <div class="form-group">
      <%= c.label :allow_supervisor_to_create_surveys, t('user_settings.supervisors_survey_permission_label') %>
      <%= c.check_box :supervisors_survey_permission %>
    </div>  

    <div class="form-group">
      <%= c.label :max_questions %>
      <%= c.number_field :max_questions %>
    </div>

    <div class="form-group">
      <%= c.label :survey_expiry_days %>
      <%= c.number_field :survey_expiry_days %>
    </div>

    <div class="form-group">
      <%= c.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/_flash_messages.html.erb
<% if flash.present? %>
  <div class="flash-messages-wrapper">
    <% flash.each do |type, messages| %>
      <% messages = messages.is_a?(Array) ? messages : [messages] %>
      <div class="<%= flash_type(type) %>">
        <ul>
          <button type="button" class="close" data-dismiss="alert"> &times; </button>
          <% messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="w-100 d-flex justify-content-center">
    <% if current_user.present? %>
      <%= link_to t('footer.home_label'), dashboard_company_path(current_user) %>
    <% else %>
      <%= link_to t('footer.home_label'), root_path %>
    <% end %>
    <%= link_to t('footer.about_label'), '#_' %>
    <%= link_to t('footer.contact_label'), '#_' %>
  </div>
  <div class="d-flex justify-content-center mt-2">
    <p class="small mb-4 mb-lg-0">&copy; <%= t 'footer.license_description' %></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-dark sticky-top custom-navbar">
  <% if current_user.present? %>
    <a class="navbar-brand" href="<%= dashboard_company_path(current_user) %>">Survey System</a>
    <div class="d-flex flex-row-reverse">
      <div class="dropdown text-white d-flex align-items-center">
        <a data-toggle="dropdown">
          <b class="text-white"><%= full_name %></b> 
          <span class="badge badge-pill badge-secondary"><%= current_user.role %></span>
          <% if current_user.image_file_name.present? %>
            <%= image_tag current_user.image.url(:thumb), class: 'rounded-circle z-depth-0 mx-2' %>
          <% else %>
            <img src="/assets/icon.jpg" class= "rounded-circle z-depth-0 mx-2" />
          <% end %>
        </a>
        <div class="dropdown-menu">
          <%= link_to "My Dashboard", dashboard_company_path(current_user), class: "dropdown-item" %>
          <% if can? :edit, current_user.user_setting %>
            <%= link_to t('header.my_settings_label'), edit_user_setting_path(current_user.user_setting), class: "dropdown-item" %>
          <% end %>
          <% if can? :edit, @current_company.company_setting %>
            <%= link_to t('header.company_settings_label'), edit_company_setting_path(current_user.company.company_setting), class: "dropdown-item" %>
          <% end %>
          <% if can? :update, current_user %>
            <%= link_to t('header.my_profile_label'), edit_user_registration_path(current_user), class: "dropdown-item" %>
          <% end %>
          <% if current_user.admin? %>
              <%= link_to "Subscription Packages", subscription_packages_company_path(current_user), class: "dropdown-item" %>
            <% end %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
      <div class="dropdown pr-2">
        <button type="button" data-user_id = "<%= current_user.id %>" class="btn btn-primary dropdown-toggle js-survey_count surveys-count" data-toggle="dropdown" id="pending_surveys">
          <i class="fa fa-bell"></i>
          <span id="survey_links" class="surveys-count-notification"></span>
        </button>
        <div id="surveys_detail" class="dropdown-menu">
        </div>
        </div>
      </div>
    </div>
  <% else %>  
    <div class="w-100 d-flex justify-content-between text-muted">
      <div>
        <a class="navbar-brand" href="\">Survey System</a>
      </div>
      <div class="d-flex justify-content-end">
        <% if @current_company.present? %>
          <%= link_to t('header.sign_in_label'), new_user_session_path, class: "nav-link" %>
        <% else %>
          <%= link_to t('header.register_label'), new_user_registration_path, class: "nav-link" %>
          <%= link_to t('header.sign_in_label'), sign_in_home_index_path, class: "nav-link" %>
        <% end %>
      </div>
    </div> 
  <% end %>
</nav>

app/views/layouts/_main_charts.html.erb
<div class="container">
  <div class="row">
    <div class='js-survey-chart col card mx-auto mb-2 p-0'>
      <div class="card-header"><b><%= t 'main_charts.surveys_stats_label' %></b></div>
      <div class="card-body">
        <!-- if there is data available for chart -->
        <% unless @surveys_stats.blank? %>
          <%= content_tag :canvas, "", id: 'surveys_stats', data: { chart_data: @surveys_stats, chart_labels:SURVEY_STATS_LABELS, chart_type: 'pie', chart_colors: GRAPH_COLORS } %>
          <div class="d-flex justify-content-center mt-1">
            <p><%= t 'main_charts.surveys_stats_description' %></p>
          </div>
        <!-- if no data is available for chart -->
        <% else %>
          <div class="vertical-horizontal-center-align">
            <h3 class="text-muted"><%= t 'main_charts.no_chart_data_label' %></h3>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-1"></div>
    <div class='js-survey-chart col card mx-auto mb-2 p-0'>
      <div class="card-header"><b><%= t 'main_charts.latest_surveys_label' %></b></div>
      <div class="card-body">
        <!-- if there is data available for chart -->
        <% unless @latest_surveys_responses_count.blank? %>
          <%= content_tag :canvas, "", id: 'latest_surveys', data: { chart_data: @latest_surveys_responses_count, chart_labels: @latest_surveys_labels, chart_type: 'bar', chart_label: 'Responses', chart_colors: GRAPH_COLORS } %>
          <div class="d-flex justify-content-center mt-1">
            <p><%= t 'main_charts.latest_surveys_description' %></p>
          </div>
          <!-- if no data is available for chart -->
        <% else %>
          <div class="vertical-horizontal-center-align">
            <h3 class="text-muted"><%= t 'main_charts.no_chart_data_label' %></h3>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_package.html.erb
<!-- Subscription Package -->
<div class="col-lg-4">
  <div class="mx-auto mb-5 mb-lg-0">
    <div class="card text-center">
      <div class="card-body">
        <h5 class="card-title"> <%= subscription_package.subscription_package_name %> </h5>
        <p class="card-text"><%= t 'package.description_label' %></p>
        <dl>
          <dt><%= t 'package.max_supervisors_label' %></dt>
          <dd> <%= subscription_package.max_supervisors %> </dd>
          <dt><%= t 'package.max_members_label' %></dt>
          <dd> <%= subscription_package.max_members %> </dd>
        </dl>
        <%= link_to t('package.subscribe_label'), update_subscription_package_company_path(subscription_package.id), class: "primary-btn" %> 
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar-style bg-dark float-left h-100 col-3 col-md-2">
  <div class="py-2 flex-grow-1">
    <div class="nav flex-sm-column">
        <% sidebar_menu.each do |content,value| %>
          <%= link_to value[:url], class: "nav-link" do %>
          <div class="row">
            <span class="fa fa-<%= value[:icon] %> mt-2 icon"></span><%= content %>
          </div>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/_user_settings_form.html.erb
<div class="col-10">
  <h3><%= t 'user_settings.user_settings_heading' %></h3>
  <%= form_for(@user_setting) do |u| %>

    <div>
      <%= u.label :show_graphs %>
      <%= u.check_box :show_graphs %>
    </div>    

    <div>
      <%= u.label :show_history %>
      <%= u.check_box :show_history %>
    </div>  

    <div>
      <%= u.submit class: "primary-btn" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey System</title>
    <!-- Latest compiled and minified CSS -->
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>

    <!-- jQuery library -->
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" %>

    <!-- Popper JS -->
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" %>

    <!-- Latest compiled JavaScript -->
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" %>

    <!-- Custom fonts for this template -->
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" %>

    <!-- Font awesome link -->
    <%= stylesheet_link_tag "http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" %>
    <!-- Chart.js -->
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" %>

    <!-- Chart.js plugin datalabels -->
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels" %>

     <!-- Fontawesome icons -->
    <%= javascript_include_tag "https://use.fontawesome.com/22018efeea.js" %>
      
    <%= javascript_include_tag "https://use.fontawesome.com/22018efeea.js" %>  
    <!-- application assets -->

    <%= stylesheet_link_tag "https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" %>

    <%= javascript_include_tag "https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" %>

    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js" %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= javascript_tag do %>
      setGlobalData('userId', <%= @current_user.id if @current_user.present? %>);
    <% end %>
  </head>
  <body>
    <!-- for guest user -->
    <% unless current_user.present? %>
      <%= render partial:'layouts/header' %>
      <div class="body-container">
        <%= yield %>
      </div>
    <!-- for logged in user -->
    <% else %>
      <div class="w-100 h-100">
        <%= render partial:'layouts/header' %>
        <div class="row no-gutters h-100 w-100 p-0 body-container">
          <div class="sidebar-style float-left h-100 col-4 col-md-2">
            <div>
              <%= render partial:'layouts/sidebar' %>  
            </div>
          </div>
          <div id="main" class="main-style my-auto float-left overflow-auto col col-md-10">
            <div class="d-flex align-items-start flex-column">
              <div class="w-100">
                <%= render partial:'layouts/flash_messages' %>
                <%= render_breadcrumbs :separator => ' / ' %>
                <div class="p-20">
                  <%= yield %>
                </div>
              </div>
              <div class="mt-auto w-100">
                <%= render partial:'layouts/footer' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</html>